const staffData = [
  {
    id: "BBE-BO-001",
    name: "Gokul",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Bobcat Operator",
    equipment: "Bobcat / Skid Steer Loader",
    trainingName: "External Bobcat Operator Training",
    trainingType: "External",
    validityType: "No Expiry",
    trainingDate: "2025-05-22",
    expiry: null,
    refresherRequired: "Company review only",
    banksmanRequired: "Yes",
    ptwRequired: "Yes",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: "certs/gokul.pdf",
    photo: "photos/gokul.jpg",
    remarks: "External training certificate has no stated expiry. Operator still subject to site authorization, PTW, equipment inspection and banksman control."
  },
  {
    id: "BBE-BO-002",
    name: "Suman",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Bobcat Operator",
    equipment: "Bobcat / Skid Steer Loader",
    trainingName: "External Bobcat Operator Training",
    trainingType: "External",
    validityType: "No Expiry",
    trainingDate: "2025-05-22",
    expiry: null,
    refresherRequired: "Company review only",
    banksmanRequired: "Yes",
    ptwRequired: "Yes",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: "certs/suman.pdf",
    photo: "photos/suman.jpg",
    remarks: "External training certificate has no stated expiry. Operator still subject to site authorization, PTW, equipment inspection and banksman control."
  },
  {
    id: "BBE-BO-003",
    name: "Lim Seng Leong",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Bobcat Operator",
    equipment: "Bobcat / Skid Steer Loader",
    trainingName: "Bobcat Skid Steer Loader Operator Safety Course",
    trainingType: "External",
    validityType: "No Expiry Stated on Certificate",
    trainingDate: "2019-07-19",
    expiry: null,
    appointmentDate: "2026-01-08",
    appointmentStatus: "Appointed",
    refresherRequired: "Company review only / as required by site or training provider",
    banksmanRequired: "Yes",
    ptwRequired: "Yes",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: null,
    certificateReference: "LIM SENG LEONG - BOBCAT.pdf",
    photo: "photos/leong_forklift.jpg",
    remarks: "Bobcat Skid Steer Loader Operator Safety Course certificate dated 19 Jul 2019 has been verified and is on file. The certificate states no expiry date. Company Bobcat / Skid Steer Loader operator appointment effective 08 Jan 2026 is also on file. Operator remains subject to site authorization, PTW, equipment inspection and banksman control."
  },
  {
    id: "BBE-BO-004",
    name: "Rashedul Islam Shamsul Haque",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Bobcat Operator",
    equipment: "Bobcat / Skid Steer Loader",
    trainingName: "Mustang Skid Steer Loader Operator Safety Course",
    trainingType: "External",
    validityType: "No Expiry Stated on Certificate",
    trainingDate: "2013-10-02",
    expiry: null,
    appointmentDate: "2026-01-08",
    appointmentStatus: "Appointed",
    refresherRequired: "Company review only / as required by site or training provider",
    banksmanRequired: "Yes",
    ptwRequired: "Yes",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: null,
    certificateReference: "ISLAM RASHEDUL- MUSTANG.pdf",
    photo: "photos/no-photo.png",
    remarks: "Mustang Skid Steer Loader Operator Safety Course certificate dated 02 Oct 2013 has been verified and is on file. The certificate states no expiry date. Company Bobcat / Skid Steer Loader operator appointment effective 08 Jan 2026 is also on file. Operator remains subject to site authorization, PTW, equipment inspection and banksman control."
  },
  {
    id: "BBE-FL-001",
    name: "Lim Seng Leong",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Forklift Operator",
    equipment: "Forklift",
    trainingName: "Forklift Operator Training",
    trainingType: "External",
    validityType: "Mandatory External Refresher (3 Years)",
    trainingDate: "2024-04-19",
    validityYears: 3,
    refresherRequired: "Yes - mandatory external refresher every 3 years",
    banksmanRequired: "Required during reversing / blind spot / congested area",
    ptwRequired: "As required by site",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: "certs/leong_forklift.pdf",
    photo: "photos/leong_forklift.jpg",
    remarks: "Forklift operation requires mandatory external refresher training every 3 years. Operator must hold valid certification. Subject to site authorization, valid PTW, equipment inspection and banksman control where required."
  },
  {
    id: "BBE-FL-002",
    name: "Ramachandran Karuppaiah",
    company: "Bryan Boiler Engineering Pte Ltd",
    role: "Forklift Operator",
    equipment: "Forklift",
    trainingName: "Forklift Operator Training",
    trainingType: "External",
    validityType: "Mandatory External Refresher (3 Years)",
    trainingDate: "2025-10-18",
    validityYears: 3,
    refresherRequired: "Yes - mandatory external refresher every 3 years",
    banksmanRequired: "Required during reversing / blind spot / congested area",
    ptwRequired: "As required by site",
    authorizationStatus: "Authorized",
    trainingEvidenceVerified: true,
    certificateLink: "certs/karuppaiah_forklift.pdf",
    photo: "photos/karuppaiah_forklift.jpg",
    remarks: "Forklift operation requires mandatory external refresher training every 3 years. Operator must hold valid certification. Subject to site authorization, valid PTW, equipment inspection and banksman control where required."
  }
];
